const fs = require('fs');
const path = require('path');
const { generateTestCases } = require('./generator');
const templates = require('./templates');

const INPUT_FILE = path.join(__dirname, '../input/requirement.txt');
const OUTPUT_FILE = path.join(__dirname, '../output/testcases.md');

async function main() {
    console.log('🚀 Starting Test Case Generator...');

    // 1. Read Input
    try {
        if (!fs.existsSync(INPUT_FILE)) {
            throw new Error(`Input file not found: ${INPUT_FILE}`);
        }
        const requirement = fs.readFileSync(INPUT_FILE, 'utf-8');
        console.log(`📖 Read requirement (${requirement.length} chars).`);

        // 2. Prepare Prompt
        const template = templates.standard_qa;
        const prompt = template.replace('{{requirement}}', requirement);

        // 3. Generate
        console.log('🤖 Generating test cases via Ollama (llama3.2)...');
        const rawResponse = await generateTestCases(prompt);

        // 4. Parse and Format
        let testCasesData;
        try {
            testCasesData = JSON.parse(rawResponse);
        } catch (e) {
            console.warn('⚠️  Could not parse JSON directly. Attempting to extract JSON block...');
            // specific logic could be added here if needed
            testCasesData = { test_cases: [], raw: rawResponse };
        }

        // Convert to Markdown
        let markdown = `# Test Cases Generated by Local LLM\n\n`;
        markdown += `**Source requirement**: _${INPUT_FILE}_\n\n`;

        if (testCasesData.test_cases && Array.isArray(testCasesData.test_cases)) {
            testCasesData.test_cases.forEach(tc => {
                markdown += `## ${tc.id}: ${tc.title}\n`;
                markdown += `**Priority**: ${tc.priority}\n\n`;
                markdown += `**Description**: ${tc.description}\n\n`;
                markdown += `**Preconditions**:\n${tc.preconditions.map(p => `- ${p}`).join('\n')}\n\n`;
                markdown += `**Steps**:\n${tc.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}\n\n`;
                markdown += `**Expected Result**: ${tc.expected_result}\n\n`;
                markdown += `---\n\n`;
            });
        } else {
            markdown += `## Raw Output (JSON Parsing Failed)\n\n`;
            markdown += `\`\`\`json\n${JSON.stringify(testCasesData, null, 2)}\n\`\`\``;
        }

        // 5. Save
        // Ensure output dir exists
        const outputDir = path.dirname(OUTPUT_FILE);
        if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

        fs.writeFileSync(OUTPUT_FILE, markdown);
        console.log(`✅ Test cases saved to: ${OUTPUT_FILE}`);

    } catch (error) {
        console.error('❌ Error:', error.message);
        process.exit(1);
    }
}

main();
